version: "3.9"
services:
  node:
    container_name: "hazadus-node"
    build: .
    command: node .output/server/index.mjs
    environment:
      - "NITRO_HOST=0.0.0.0"
      - "NITRO_PORT=80"
    ports:
      - "80:80"
